#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alex Moncks
"""Tables of the geo3d BASIC ROM, written to stdout as z80asm source
(build.sh: out/g3tab.asm and out/g3ang.asm, included by g3basic.asm).

  gen_tables.py sin   bank 2: the first quarter of a sine wave in Q2.14,
                      4096 words, entry i = round(16384 * sin(i * 90 / 4096
                      degrees)), i = 0..4095 (sin 90 = 16384 is not stored:
                      getsin returns it). Exactly one 8 KB bank.
  gen_tables.py ang   bank 0: angtab, 360 words, (r * 65536 + 180) / 360:
                      a whole number of degrees r in 65536 units per turn,
                      rounded (dacang's fast path for integer angles).
check_frames.py and test_math.py import these for their copy of the math.
"""
import math
import sys


def sintab():
    return [int(math.floor(16384 * math.sin(i * math.pi / 8192) + 0.5)) for i in range(4096)]


def angtab():
    return [(r * 65536 + 180) // 360 for r in range(360)]


def emit(label, words, note):
    print("; generated by gen_tables.py, do not edit: " + note)
    if label:
        print(label + ":")
    for k in range(0, len(words), 16):
        print("        defw " + ",".join(str(v) for v in words[k:k + 16]))


def main():
    what = sys.argv[1] if len(sys.argv) > 1 else "sin"
    if what == "sin":
        emit(None, sintab(), "4096 words, sin(i * 90 / 4096)")
    elif what == "ang":
        emit("angtab", angtab(), "360 words, (r * 65536 + 180) / 360")
    else:
        sys.exit("gen_tables.py: sin or ang")


if __name__ == "__main__":
    main()
