#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alex Moncks
"""Generates geo_face_tables.asm for geo3d_faces_demo.asm: the word "GEO3D"
as extruded segmented blocks, a two-ramp palette, a light direction and the
same looping rotation table as gen_tables.py."""
import math

from gen_tables import FRAMES, matrix as spin_matrix, words_db, db_lines

U = 22            # grid unit (world units)
DEPTH = 26        # half thickness of the letters
GAP = 0.14        # gap between segments, in grid units
TZ = 820

# segments per letter on a 5 x 7 grid: (x, y, w, h), y up
FONT = {
    "G": [(0, 6, 5, 1), (0, 1, 1, 5), (0, 0, 5, 1), (4, 1, 1, 2), (2, 3, 3, 1)],
    "E": [(0, 6, 5, 1), (0, 1, 1, 5), (0, 0, 5, 1), (1, 3, 3, 1)],
    "O": [(0, 6, 5, 1), (0, 0, 5, 1), (0, 1, 1, 5), (4, 1, 1, 5)],
    "3": [(0, 6, 5, 1), (1, 3, 3, 1), (0, 0, 5, 1), (4, 1, 1, 5)],
    "D": [(0, 0, 1, 7), (1, 6, 3, 1), (1, 0, 3, 1), (4, 1, 1, 5)],
}
TEXT = "GEO3D"
PITCH = 6.2       # letter advance, grid units

BASE_CAP, BASE_SIDE = 1, 8          # colour ramps: 1..7 and 8..14
LIGHT = (-0.45, 0.55, -0.70)        # towards the light, camera space (y up, z forward)


def boxes():
    width = PITCH * (len(TEXT) - 1) + 5
    out = []
    for n, ch in enumerate(TEXT):
        for (x, y, w, h) in FONT[ch]:
            x0 = (n * PITCH + x + GAP / 2 - width / 2) * U
            x1 = (n * PITCH + x + w - GAP / 2 - width / 2) * U
            y0 = (y + GAP / 2 - 3.5) * U
            y1 = (y + h - GAP / 2 - 3.5) * U
            out.append((round(x0), round(x1), round(y0), round(y1)))
    return out


def model():
    verts, faces = [], []
    for (x0, x1, y0, y1) in boxes():
        first = len(verts)
        corner = {}
        for ix, x in enumerate((x0, x1)):
            for iy, y in enumerate((y0, y1)):
                for iz, z in enumerate((-DEPTH, DEPTH)):
                    corner[(ix, iy, iz)] = len(verts)
                    verts.append((x, y, z))
        for axis in range(3):
            for side in (0, 1):
                n = [0, 0, 0]
                n[axis] = 1 if side else -1
                a, b = [k for k in range(3) if k != axis]
                cyc = []
                for u, w in ((0, 0), (1, 0), (1, 1), (0, 1)):
                    key = [0, 0, 0]
                    key[axis], key[a], key[b] = side, u, w
                    cyc.append(tuple(key))
                p = [verts[corner[c]] for c in cyc]
                e1 = [p[1][k] - p[0][k] for k in range(3)]
                e2 = [p[2][k] - p[0][k] for k in range(3)]
                cr = (e1[1] * e2[2] - e1[2] * e2[1], e1[2] * e2[0] - e1[0] * e2[2], e1[0] * e2[1] - e1[1] * e2[0])
                if sum(cr[k] * n[k] for k in range(3)) < 0:
                    cyc.reverse()
                base = BASE_CAP if axis == 2 else BASE_SIDE
                faces.append(([corner[c] for c in cyc], [v * 16384 for v in n], base))
    assert len(verts) <= 255 and len(faces) <= 255, (len(verts), len(faces))
    return verts, faces


def palette():
    """V9938 palette: 0 black, 1..7 gold ramp, 8..14 teal ramp, 15 white."""
    def ramp(rgb):
        return [tuple(min(7, round(c * (0.28 + 0.72 * l / 6))) for c in rgb) for l in range(7)]
    cols = [(0, 0, 0)] + ramp((7, 5, 1)) + ramp((1, 5, 7)) + [(7, 7, 7)]
    b = []
    for r, g, bl in cols:
        b += [(r << 4) | bl, g]
    return cols, b


def main():
    verts, faces = model()
    ln = math.sqrt(sum(c * c for c in LIGHT))
    light = [round(c / ln * 16384) for c in LIGHT]
    cols, pal = palette()
    lines = ["; generated by gen_face_tables.py, do not edit",
             f"NVERT:\tequ {len(verts)}", f"NFACE:\tequ {len(faces)}", f"NFRAMES:\tequ {FRAMES}", ""]
    vb = []
    for v in verts:
        vb += words_db(v)
    lines += db_lines("model_vertices", vb)
    fb = []
    for ids, n, base in faces:
        fb += ids + words_db(n) + [base]
    lines += db_lines("model_faces", fb, per=11)
    lines += db_lines("light_words", words_db(light))
    lines += db_lines("palette", pal, per=16)
    mt = []
    for k in range(FRAMES):
        m = spin_matrix(k)
        mt += words_db(m[:9] + [0, 0, TZ])
    lines += db_lines("matrix_table", mt, per=24)
    open("geo_face_tables.asm", "w").write("\n".join(lines) + "\n")
    open("face_palette.txt", "w").write("\n".join(f"{r} {g} {b}" for r, g, b in cols) + "\n")
    print(f"GEO3D: {len(verts)} vértices, {len(faces)} faces, luz {light}, {FRAMES} matrizes")


if __name__ == "__main__":
    main()
