#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alex Moncks
"""Generates geo_tex_tables.asm for geo3d_tex_demo.asm: the GEO3D block
letters with textured front/back caps (LRMM) and solid shaded sides (LINE),
plus the texture: 256 x 32 texels, stored as 7 pre-shaded copies stacked in
VRAM page 2 (y = 512 + 32 * level), SCREEN 5 nibble packing."""
import math

from gen_face_tables import model, palette, LIGHT, TZ
from gen_tables import FRAMES, matrix as spin_matrix, words_db, db_lines

TEX_W, TEX_H = 256, 32
TEXY = 512
TSTRIDE = 32
BASE_CAP_TEX = 0x80 | 1       # textured, gold ramp for the outside-window colour


def texel(x, y):
    """(ramp base, darkening offset) of a texel: diagonal gold/teal bands,
    a darker 16-texel grid and small 'chip' dots."""
    base = 1 if ((x + y) // 12) % 2 == 0 else 8
    off = 0
    if x % 16 == 0 or y % 16 == 0:
        off = 3
    elif (x % 16 in (7, 8)) and (y % 16 in (7, 8)):
        off = 0
        base = 8 if base == 1 else 1
    return base, off


def texture_copies():
    """Returns VRAM bytes for rows TEXY .. TEXY + 7*TSTRIDE - 1."""
    rows = []
    for lvl in range(7):
        for y in range(TEX_H):
            row = bytearray(128)
            for x in range(TEX_W):
                base, off = texel(x, y)
                c = base + max(0, lvl - off)
                if x & 1:
                    row[x >> 1] |= c
                else:
                    row[x >> 1] |= c << 4
            rows.append(row)
    return b"".join(rows)


def uv_mapping(verts, faces):
    xs = [v[0] for v in verts]
    ys = [v[1] for v in verts]
    x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
    out, tex_faces = [], []
    for ids, n, base in faces:
        if n[2] != 0:                               # front / back cap
            uv = []
            for i in ids:
                x, y, _ = verts[i]
                uv += [round((x - x0) / (x1 - x0) * (TEX_W - 1)),
                       round((y1 - y) / (y1 - y0) * (TEX_H - 1))]
            out.append(uv)
            tex_faces.append((ids, n, BASE_CAP_TEX))
        else:
            out.append([0] * 8)
            tex_faces.append((ids, n, base))
    return tex_faces, out


def main():
    verts, faces = model()
    faces, uvs = uv_mapping(verts, faces)
    ln = math.sqrt(sum(c * c for c in LIGHT))
    light = [round(c / ln * 16384) for c in LIGHT]
    cols, pal = palette()
    tex = texture_copies()
    lines = ["; generated by gen_tex_tables.py, do not edit",
             f"NVERT:\tequ {len(verts)}", f"NFACE:\tequ {len(faces)}", f"NFRAMES:\tequ {FRAMES}",
             f"TEXY:\tequ {TEXY}", f"TSTRIDE:\tequ {TSTRIDE}", f"TEXBYTES:\tequ {len(tex)}", ""]
    vb = []
    for v in verts:
        vb += words_db(v)
    lines += db_lines("model_vertices", vb)
    fb = []
    for ids, n, base in faces:
        fb += ids + words_db(n) + [base]
    lines += db_lines("model_faces", fb, per=11)
    lines += db_lines("model_uv", [b for uv in uvs for b in uv], per=16)
    lines += db_lines("light_words", words_db(light))
    lines += db_lines("palette", pal, per=16)
    mt = []
    for k in range(FRAMES):
        m = spin_matrix(k)
        mt += words_db(m[:9] + [0, 0, TZ])
    lines += db_lines("matrix_table", mt, per=24)
    lines += db_lines("texture", list(tex), per=32)
    open("geo_tex_tables.asm", "w").write("\n".join(lines) + "\n")
    open("tex_init.hex", "w").write("\n".join(f"{b:02x}" for b in tex) + "\n")
    ntex = sum(1 for f in faces if f[2] & 0x80)
    print(f"GEO3D texturizado: {len(verts)} vértices, {len(faces)} faces ({ntex} texturizadas), "
          f"textura {TEX_W}x{TEX_H} x 7 cópias = {len(tex)} bytes")


if __name__ == "__main__":
    main()
