#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alex Moncks
"""Generates geo_tables.asm: model (vertices + edges) and a table of
precomputed rotation matrices, so the Z80 never multiplies anything."""
import math

FRAMES = 128   # power of two: the Z80 wraps with AND
TZ = 900


def q14(x):
    return max(-32768, min(32767, round(x * 16384)))


def s16(x):
    return x & 0xFFFF


def model():
    s = 150
    v = [(x, y, z) for x in (-s, s) for y in (-s, s) for z in (-s, s)]
    e = [(i, j) for i in range(8) for j in range(i + 1, 8) if bin(i ^ j).count("1") == 1]
    # inner octahedron
    o = 90
    base = len(v)
    v += [(o, 0, 0), (-o, 0, 0), (0, o, 0), (0, -o, 0), (0, 0, o), (0, 0, -o)]
    pairs = [(0, 2), (0, 3), (0, 4), (0, 5), (1, 2), (1, 3), (1, 4), (1, 5),
             (2, 4), (2, 5), (3, 4), (3, 5)]
    e += [(base + a, base + b) for a, b in pairs]
    return v, e


def matrix(k):
    # periodic in k: frame FRAMES == frame 0, so the spin loops without a jump
    t = 2 * math.pi * k / FRAMES
    ay = t                              # one full turn around Y
    ax = 0.45 + 0.30 * math.sin(t)      # gentle nod around X
    cy, sy = math.cos(ay), math.sin(ay)
    cx, sx = math.cos(ax), math.sin(ax)
    # R = Rx * Ry
    r = [[cy, 0, sy],
         [sx * sy, cx, -sx * cy],
         [-cx * sy, sx, cx * cy]]
    return [q14(r[i][j]) for i in range(3) for j in range(3)] + [0, 0, TZ]


def words_db(ws):
    b = []
    for w in ws:
        b += [s16(w) & 0xFF, s16(w) >> 8]
    return b


def db_lines(label, data, per=12):
    out = [f"{label}:"]
    for i in range(0, len(data), per):
        out.append("\tdb " + ",".join(f"0x{x:02x}" for x in data[i:i + per]))
    return out


def main():
    v, e = model()
    lines = ["; generated by gen_tables.py, do not edit", f"NVERT:\tequ {len(v)}", f"NEDGE:\tequ {len(e)}",
             f"NFRAMES:\tequ {FRAMES}", ""]
    vb = []
    for p in v:
        vb += words_db(p)
    lines += db_lines("model_vertices", vb)
    eb = [x for pair in e for x in pair]
    lines += db_lines("model_edges", eb)
    mt = []
    for k in range(FRAMES):
        mt += words_db(matrix(k))
    lines += db_lines("matrix_table", mt, per=24)
    open("geo_tables.asm", "w").write("\n".join(lines) + "\n")
    print(f"{len(v)} vértices, {len(e)} arestas, {FRAMES} matrizes ({FRAMES * 24} bytes)")


if __name__ == "__main__":
    main()
