#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alex Moncks
"""Tests of the MoonSound MOD player (geo3d_modplay.asm, modelled by modplay.py),
alone or in the demo ROM.

--z80: builds modplay_test.asm with the MOD (modplay.Song.pack) and runs it in
the Z80 emulator (pip z80) with an emulated MoonSound (opl4emu.py), in real
time (T-states): the sample RAM the upload fills, byte for byte; mod_start's
writes; every wave register write of every tick (between two clears of timer
2's flag) against modplay.py's model of the player; every tone header it
loads a RAM tone whose header points into the samples; the timer 2
periods; no tick lost; the tick and key-on latencies behind the timer. Fast (no
openMSX), so --selftest runs it on MODs made here: one per group of effects
(every effect the player takes, 4, 6 and 8 channels, tempo changes, jumps,
loops, empty samples) and random ones (--fuzz N): the player against its
model on songs it was not written for. The model plays what ProTracker plays
(modplay.Player, as OpenMPT, which the audio test checks); in these MODs it
is the model without play positions (Player(track=False)), the player's.

openMSX (default): builds the test ROM, runs it in openMSX with a MoonSound
(extension moonsound_test: 640 KB sample RAM). With --rom: runs the demo ROM
(build_rom.py --music MOD) on C-BIOS_V9968_JP + geo3d with a MoonSound
(--ext: the extensions, default "geo3d moonsound"; for the 88h profile
"HRA_V9968 geo3d88 moonsound"), chooses English at --key-at s, and follows
the crawl's music from mod_start to the MOD's stop, with the demo running.
It checks:

  trace   the sample RAM (tone headers and samples) as the chip sees it
          when the song starts, against modplay.py's; every wave register
          write the Z80 makes (openMSX watchpoints on 7Eh/7Fh) against
          modplay.py's, tick by tick; the timer 2 periods;
          the tick times (the flag clears) against the OPL4 timer and
          against ProTracker's 2.5 / BPM s per tick; the key-on times.
  audio   openMSX's recording (the mix, and each MOD channel: the sum of
          its three OPL4 channels) against OpenMPT playing the original MOD
          file (openmpt123 set up like the OPL4: linear interpolation, no
          Amiga resampler or filter, no volume ramping, the Amiga's hard
          panning), note by note: onset, pitch (resampled correlation),
          level, and the loops (the sound late in long notes); the mix frame
          by frame and its lag every 2 s (drift). Also the mix's spectrum
          against OpenMPT as a player plays it by default (Amiga resampler
          and filter): the OPL4 interpolates linearly and has no Amiga
          filter, so it is brighter above 10 kHz.
  --rom   also: the upload (its first unit to its end, and the menu), the
          longest times from one mod_poll call to the next while the song
          plays (a call that plays a tick counts in), and the crawl's page
          flips in vertical blanks (against --flips-ref, a d/f time log of
          another run, e.g. of a ROM without the MOD player).

Usage: test_modplay.py MOD [--seconds S] [--fade F] [--gap N] [--work DIR]
                       [--preview DIR] [--tag T] [--no-openmsx]
                       [--rom ROM [--labels FILE] [--ext "EXT ..."] [--key-at S]
                        [--flips-ref FILE]]
       test_modplay.py MOD --z80 [--kb KB] [--gap N]
       test_modplay.py --selftest [--fuzz N] [--seed S]
Everything made from the MOD (ROM, recordings, renders) goes to --work
(default rom/out/modplay_test, git-ignored) and --preview: keep it out of
the repository. WSL / Linux: needs z80asm, the z80 package, numpy; openMSX
(OPENMSX, OPENMSX_SYSTEM_DATA) and openmpt123 for the openMSX tests.
"""
import argparse
import json
import math
import os
import random
import shutil
import struct
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import modplay  # noqa: E402
import opl4emu  # noqa: E402

RATE = 44100
BANK = modplay.BANK
OPENMSX = os.environ.get("OPENMSX", os.path.expanduser("~/openMSX/derived/x86_64-linux-opt/bin/openmsx"))
WAVE_DEV = "Sunrise MoonSound wave"


def labels_of(path):
    labels = {}
    for line in open(path):
        p = line.replace(":", " ").split()
        if len(p) >= 3 and p[1] == "equ":
            labels[p[0]] = int(p[2].lstrip("$").replace("0x", ""), 16)
    return labels


# ------------------------------------------------------------------ build
def build(song, work, gap):
    banks, equ = song.pack(1)
    open(os.path.join(work, "rom_mod.asm"), "w").write(equ)
    open(os.path.join(work, "rom_test.asm"), "w").write(
        f"; generated by test_modplay.py\nT_GAP:  equ {gap}\n")
    subprocess.run(["z80asm", "-I", work, "-I", HERE, "-o", "bank0.bin", "--label=labels.txt",
                    os.path.join(HERE, "modplay_test.asm")], cwd=work, check=True)
    bank0 = open(os.path.join(work, "bank0.bin"), "rb").read()
    assert len(bank0) <= BANK, len(bank0)
    rom = bytearray(bank0) + bytes(BANK - len(bank0))
    for b in banks:
        rom += b + bytes(BANK - len(b))
    n = len(rom) // BANK
    rom += bytes(((1 << (n - 1).bit_length()) - n) * BANK)
    path = os.path.join(work, "modplay_test.rom")
    open(path, "wb").write(rom)
    return path, len(bank0), labels_of(os.path.join(work, "labels.txt"))


# -------------------------------------------------------------------- Z80
def run_z80(rom, labels, kb=640, limit_s=None):
    """The test ROM in the Z80 emulator, real time (a 3.58 MHz Z80; the pip
    z80 counts no MSX M1 wait, so it is a little fast), with an emulated
    MoonSound of kb KB. -> (MoonSound, info)."""
    import z80
    m = z80.Z80Machine()
    m.set_memory_block(0x4000, rom[0:BANK])
    m.set_memory_block(0x0024, b"\xC9")                     # ENASLT
    m.set_memory_block(0x0138, b"\xC9")                     # RSLREG
    m.set_memory_block(0xFCC1, bytes(5))
    m.sp = 0xF37D
    m.pc = rom[2] | rom[3] << 8
    ms = opl4emu.MoonSound(kb)
    run = 200000
    st = {"t0": 0}

    def now():
        return st["t0"] + run - m.ticks_to_stop

    def on_out(port, v):
        ms.port_out(port & 0xFF, v, now())

    def on_in(port):
        v = ms.port_in(port & 0xFF, now())
        return 0xFF if v is None else v
    m.set_output_callback(on_out)
    m.set_input_callback(on_in)
    stops = {0x0024, 0x0138, labels["mp_setbank"], labels["mod_upload"], labels["mod_start"]}
    for a in stops:
        m.set_breakpoint(a)
    info = {}
    limit = (limit_s or 1e9) * opl4emu.T_HZ
    while True:
        m.ticks_to_stop = run
        m.run()
        st["t0"] += run - m.ticks_to_stop
        pc = m.pc
        if pc in stops:
            if pc == 0x0138:
                m.a = 0b00010100                            # slot 1 in pages 1 and 2
            elif pc == labels["mp_setbank"]:
                b = m.a
                m.set_memory_block(0x8000, bytes(rom[b * BANK:(b + 1) * BANK]).ljust(BANK, b"\xFF"))
            elif pc == labels["mod_upload"]:
                ms.counting = True
                info["up0"] = st["t0"]
            elif pc == labels["mod_start"]:
                ms.counting = False
                info["start"] = st["t0"]
            m.ticks_to_stop = run
            m.step_over_breakpoint()
            st["t0"] += run - m.ticks_to_stop
        phase = m.memory[0xC000]
        if phase in (3, 0xEE) or m.halted or st["t0"] > limit:
            break
    info.update(phase=phase, blocks=m.memory[0xC001], end=st["t0"],
                ticks=m.memory[labels["mp_ticks"]] | m.memory[labels["mp_ticks"] + 1] << 8)
    return ms, info


def check_play(song, ms, t_from=0.0):
    """What the emulated MoonSound got from the player against the model:
    -> (ok, report dict)."""
    seg = opl4emu.segments(ms, t_from)
    if seg is None:
        return False, dict(error="the song never started (timer 2 never on)")
    stopped = seg["t_stop"] < float("inf")
    bad, last_ok = opl4emu.match_ticks(seg["segs"], song.writes, song.heads, stopped)
    init_ok = seg["init"] == song.writes_start
    per = seg["periods"]
    per_ok = per == song.counts[:len(per)] and len(per) >= min(len(seg["segs"]), len(song.counts))
    rep = dict(ticks=len(seg["segs"]), model_ticks=len(song.writes) - 1, stopped=stopped,
               end_reached=stopped and len(seg["segs"]) == len(song.writes),
               start_writes_ok=init_ok, ticks_ok=not bad and last_ok, periods_ok=per_ok,
               periods=len(per), after_stop=len(seg["tail"]), load_clashes=len(ms.load_clash),
               bad_tone_loads=len(ms.bad_loads))
    if bad or not last_ok:
        i = bad[0] if bad else len(seg["segs"]) - 1
        rep["first_bad_tick"] = i
        rep["got"] = seg["segs"][i][:14]
        rep["want"] = (song.writes[i] if i < len(song.writes) else [])[:14]
    if not init_ok:
        rep["start_got"], rep["start_want"] = seg["init"][:10], song.writes_start[:10]
    # timing: timer 2's overflows (the next tick due) against the flag clears
    # (the poll that plays it); a tick is lost if the next overflow comes first
    ov = [t for t in ms.ov2 if seg["t_start"] < t < seg["t_stop"]]
    cl = seg["clears"]
    lat = [c - o for o, c in zip(ov, cl)]
    lost = [i for i in range(min(len(ov) - 1, len(cl))) if cl[i] >= ov[i + 1]]
    marks = [seg["t_start"]] + cl
    kon, kk = [], 0
    for t, r, v in ms.wave:
        if t < seg["t_start"] or t > seg["t_stop"]:
            continue
        while kk + 1 < len(marks) and t >= marks[kk + 1]:
            kk += 1
        if 0x68 <= r < 0x80 and v & 0x80:
            kon.append(t - (seg["t_start"] if kk == 0 else ov[kk - 1] if kk - 1 < len(ov) else marks[kk]))
    ms_ = 1e3 / opl4emu.T_HZ
    rep.update(lost=len(lost), tick_latency_ms_max=round(max(lat) * ms_, 3) if lat else None,
               keyon_latency_ms_max=round(max(kon) * ms_, 3) if kon else None, keyons=len(kon))
    ok = (init_ok and not bad and last_ok and per_ok and not lost and not seg["tail"] and not ms.load_clash
          and not ms.bad_loads)
    return ok, rep


def z80_test(song, work, kb=640, gap=0, quiet=False):
    """Builds the test ROM, runs it in the Z80 emulator, checks the upload
    and the play. -> (ok, report)."""
    rom_path, b0, labels = build(song, work, gap)
    rom = open(rom_path, "rb").read()
    t0 = time.time()
    ms, info = run_z80(rom, labels, kb, song.seconds + 10)
    rep = dict(emulator_s=round(time.time() - t0, 1), phase=info["phase"], blocks_found=info["blocks"],
               module_bytes=labels["mp_new2"] + 20 - labels["mod_reset"], bank0_bytes=b0)
    if song.rt.blocks * 128 > kb:
        ok = info["phase"] == 0xEE
        rep["too_little_ram"] = ok
        return ok, rep
    img = song.image
    rep["image_ok"] = ms.mem_n == len(img) and bytes(ms.ram[:len(img)]) == img
    rep["upload_ms"] = round((ms.mem_t[1] - ms.mem_t[0]) / opl4emu.T_HZ * 1e3, 1) if ms.mem_t else None
    ok, play = check_play(song, ms)
    rep.update(play)
    ok = ok and rep["image_ok"] and info["phase"] == 3 and rep.get("end_reached")
    return ok, rep


# ---------------------------------------------------------------- self test
PT = modplay.PT_TABLE


def mod_file(nch, samples, order, pats, title=b"geo3d test"):
    """A 31-sample MOD: samples [(data bytes, volume, finetune, loop start,
    loop length (bytes, 0: none))], patterns [64 rows of nch cells (sample,
    period, effect, parameter)]."""
    tag = {4: b"M.K.", 6: b"6CHN", 8: b"8CHN"}.get(nch, b"%dCHN" % nch)
    head = bytearray(title.ljust(20, b"\0")[:20])
    for i in range(31):
        d, vol, ft, ls, ll = samples[i] if i < len(samples) else (b"", 0, 0, 0, 0)
        head += b"smp%d" % (i + 1) + bytes(22 - len(b"smp%d" % (i + 1)))
        head += struct.pack(">HBBHH", len(d) // 2, ft & 15, vol, ls // 2, max(1, ll // 2))
    head += bytes([len(order), 127]) + bytes(order) + bytes(128 - len(order)) + tag
    body = bytearray()
    for p in pats:
        for row in p:
            for s, per, e, x in row:
                body += bytes([(s & 0xF0) | (per >> 8), per & 0xFF, ((s & 15) << 4) | e, x])
    for d, *_ in samples:
        body += d
    return bytes(head + body)


def wave(n, kind, seed=0):
    rnd = random.Random(seed)
    out = bytearray()
    for i in range(n):
        if kind == "saw":
            v = (i * 7) % 200 - 100
        elif kind == "sq":
            v = 90 if (i // 16) % 2 else -90
        else:
            v = rnd.randint(-120, 120)
        out.append(v & 0xFF)
    return bytes(out)


def std_samples():
    """1 looped saw, 2 one-shot noise, 3 empty, 4 looped square (finetune
    -3), 5 one-shot saw (loop start past the end: a one-shot), 6 long loop,
    7 a loop of one word (a one-shot)."""
    return [(wave(4000, "saw"), 64, 0, 1000, 2000),
            (wave(3000, "noise", 1), 50, 0, 0, 0),
            (b"", 40, 0, 0, 0),
            (wave(2048, "sq"), 60, 13, 0, 2048),
            (wave(1500, "saw"), 64, 5, 1600, 100),
            (wave(20000, "noise", 2), 30, 7, 5000, 15000),
            (wave(900, "sq"), 64, 0, 0, 2)]


def empty(nch):
    return [[(0, 0, 0, 0)] * nch for _ in range(64)]


def put(p, row, ch, s=0, note=None, e=0, x=0):
    per = PT[note] if note is not None else 0
    p[row] = list(p[row])
    p[row][ch] = (s, per, e, x)


def cover_songs():
    """(name, channels, samples, order, patterns): every effect the player
    takes, and the song-wide ones."""
    songs = []
    # 1: notes, volume, porta, arpeggio, fine slides, finetune, cut, delay
    p = empty(4)
    put(p, 0, 0, 1, 12, 0xC, 40)
    put(p, 0, 1, 4, 24)
    put(p, 0, 2, 2, 0)
    put(p, 0, 3, 6, 5, 0xA, 0x02)
    put(p, 2, 0, 0, None, 0x1, 3)
    put(p, 3, 1, 0, None, 0x2, 5)
    put(p, 4, 0, 0, None, 0x0, 0x37)
    put(p, 5, 0, 0, None, 0x0, 0x4C)
    put(p, 6, 1, 1, 17, 0x3, 4)
    put(p, 7, 1, 0, None, 0x3, 0)
    put(p, 8, 1, 0, 30, 0x5, 0x20)
    put(p, 9, 1, 0, None, 0x5, 0x03)
    put(p, 10, 0, 0, None, 0xE, 0x13)
    put(p, 11, 0, 0, None, 0xE, 0x2F)
    put(p, 12, 0, 1, 20, 0xE, 0x57)
    put(p, 13, 0, 0, None, 0xE, 0xA3)
    put(p, 14, 0, 0, None, 0xE, 0xB9)
    put(p, 15, 0, 0, None, 0xE, 0xC2)
    put(p, 16, 0, 1, 9, 0xE, 0xD3)
    put(p, 17, 0, 1, 9, 0xE, 0xD9)                  # the delay past the row's end
    put(p, 18, 2, 0, None, 0xE, 0xC0)
    put(p, 19, 2, 5, 33, 0xA, 0x40)
    put(p, 20, 2, 0, None, 0xA, 0x0F)
    put(p, 21, 3, 0, None, 0xC, 80)
    put(p, 22, 3, 3, 10)                            # the empty sample: a stop
    put(p, 23, 3, 7, 11)
    put(p, 24, 0, 1, 35, 0x1, 0xFF)                 # slides to the limits
    put(p, 26, 1, 4, 0, 0x2, 0xFF)
    put(p, 28, 0, 0, None, 0x0, 0xFF)
    put(p, 30, 2, 6, 0, 0x0, 0x9F)
    put(p, 32, 1, 0, 35, 0x3, 0xFF)
    put(p, 34, 0, 2, 2, 0xE, 0x93)                  # a retrigger every 3 ticks
    put(p, 35, 0, 0, None, 0xE, 0x91)
    put(p, 36, 0, 0, None, 0xE, 0x92)
    put(p, 37, 1, 4, 13, 0xE, 0x5F)
    put(p, 38, 1, 0, 13, 0xE, 0x50)
    put(p, 40, 3, 1, 20, 0x3, 8)                    # tone porta on a new channel
    put(p, 42, 2, 0, 20, 0x3, 2)                    # tone porta with nothing sounding
    put(p, 44, 0, 0, 25)                            # a note without instrument
    put(p, 46, 0, 0, None, 0xE, 0x90)
    put(p, 48, 3, 1, 3, 0xC, 0)
    put(p, 50, 3, 0, None, 0xE, 0xA0)
    songs.append(("effects", 4, std_samples(), [0], [p]))
    # 2: 9xx, stacking, retrigger with the stack, E9x on the note row
    p = empty(4)
    put(p, 0, 0, 1, 12, 0x9, 8)
    put(p, 2, 0, 0, 14, 0x9, 0)                     # the memory, stacked
    put(p, 4, 0, 0, 16)                             # the stack alone
    put(p, 6, 0, 0, None, 0xE, 0x92)
    put(p, 8, 0, 1, 18, 0x9, 4)                     # an instrument: the stack from 0
    put(p, 10, 1, 6, 12, 0x9, 0x30)
    put(p, 12, 1, 0, 14, 0x9, 0x60)                 # 9xx past the end: the end
    put(p, 14, 2, 2, 12, 0x9, 2)
    put(p, 16, 2, 0, 12, 0x9, 0xFF)
    put(p, 18, 3, 5, 12, 0x9, 1)
    put(p, 20, 3, 0, 12, 0xE, 0x92)
    songs.append(("offsets", 4, std_samples(), [0], [p]))
    # 3: song-wide: speed, tempo, break (decimal), jump, pattern loop, row delay
    a, b, c = empty(4), empty(4), empty(4)
    put(a, 0, 0, 1, 12, 0xF, 3)
    put(a, 0, 1, 4, 17, 0xF, 0xA0)                  # tempo 160: from the next tick
    put(a, 1, 2, 6, 5)
    put(a, 2, 0, 0, 14, 0xE, 0x60)
    put(a, 3, 1, 0, 19)
    put(a, 4, 0, 0, 16, 0xE, 0x62)                  # back to row 2, twice
    put(a, 5, 0, 0, 12, 0xF, 1)
    put(a, 6, 3, 2, 7, 0xE, 0xE2)                   # the row 3 times
    put(a, 7, 1, 0, 21, 0xF, 31)
    put(a, 8, 0, 0, None, 0xF, 4)
    put(a, 8, 1, 0, None, 0xF, 0x20)                # 32 BPM
    put(a, 9, 2, 0, None, 0xF, 0xFF)                # 255 BPM
    put(a, 10, 3, 0, None, 0xD, 0x32)               # break to row 32 of the next
    put(b, 32, 0, 1, 24, 0xF, 6)
    put(b, 33, 1, 0, None, 0xF, 0x7D)
    put(b, 36, 2, 6, 10, 0xB, 3)                    # jump to position 3
    put(c, 0, 0, 7, 1, 0xE, 0xE1)
    put(c, 0, 1, 0, None, 0xE, 0xE5)                # the first EEx counts
    put(c, 2, 2, 4, 30, 0xD, 0x99)                  # break past 63: row 0
    songs.append(("song", 4, std_samples(), [0, 1, 2, 2, 1], [a, b, c]))
    # 4, 5: 6 and 8 channels (rows of 24 and 32 bytes)
    for nch in (6, 8):
        p = empty(nch)
        for r in range(0, 64, 2):
            for ch in range(nch):
                if (r // 2 + ch) % 3 == 0:
                    put(p, r, ch, 1 + (r + ch) % 7, (r + 3 * ch) % 36, (0, 0xA, 0xC, 1)[ch % 4],
                        (0, 0x01, 30 + ch, 2)[ch % 4])
        songs.append((f"{nch} channels", nch, std_samples(), [0, 0], [p]))
    return songs


def random_song(rnd):
    nch = rnd.choice([4, 4, 4, 6, 8])
    smps = std_samples()
    fx = [(0, lambda: rnd.randint(1, 255)), (1, lambda: rnd.randint(0, 40)), (2, lambda: rnd.randint(0, 40)),
          (3, lambda: rnd.randint(0, 64)), (5, lambda: rnd.choice([0x10, 0x03, 0x40])),
          (9, lambda: rnd.randint(0, 20)), (0xA, lambda: rnd.choice([0x10, 0x02, 0x80, 0x0F])),
          (0xC, lambda: rnd.randint(0, 80)), (0xE, lambda: rnd.choice(
              [0x10 | rnd.randint(0, 15), 0x20 | rnd.randint(0, 15), 0x50 | rnd.randint(0, 15),
               0x90 | rnd.randint(0, 6), 0xA0 | rnd.randint(0, 15), 0xB0 | rnd.randint(0, 15),
               0xC0 | rnd.randint(0, 6), 0xD0 | rnd.randint(0, 8), 0x60 | rnd.randint(0, 2),
               0xE0 | rnd.randint(0, 2)])),
          (0xF, lambda: rnd.choice([rnd.randint(1, 8), rnd.randint(0x20, 0xFF)])),
          (0xD, lambda: rnd.choice([0, 0x10, 0x32, 0x63])), (0xB, lambda: rnd.randint(0, 4))]
    npat = rnd.randint(1, 3)
    pats = []
    for _ in range(npat):
        p = empty(nch)
        for r in range(64):
            for ch in range(nch):
                if rnd.random() < 0.3:
                    s = rnd.choice([0, 0, 1, 2, 3, 4, 5, 6, 7])
                    note = rnd.randint(0, 35) if rnd.random() < 0.7 else None
                    e, x = (0, 0)
                    if rnd.random() < 0.6:
                        e, g = rnd.choice(fx)
                        x = g()
                        if e == 0xB and rnd.random() < 0.8:
                            e, x = 0, 0                 # few jumps
                    put(p, r, ch, s, note, e, x)
        pats.append(p)
    order = [rnd.randrange(npat) for _ in range(rnd.randint(1, 5))]
    return ("random", nch, smps, order, pats)


def selftest(work, fuzz, seed):
    os.makedirs(work, exist_ok=True)
    songs = cover_songs()
    rnd = random.Random(seed)
    songs += [random_song(rnd) for _ in range(fuzz)]
    npass = 0
    for i, (name, nch, smps, order, pats) in enumerate(songs):
        path = os.path.join(work, f"self{i}.mod")
        open(path, "wb").write(mod_file(nch, smps, order, pats))
        try:
            song = modplay.Song(path, 16.0, 1.0, strict=False)
        except ValueError as e:
            print(f"{i:3d} {name:12s}: the model refuses it: {e}")
            continue
        ok, rep = z80_test(song, work)
        npass += ok
        keep = {k: rep[k] for k in ("ticks", "model_ticks", "image_ok", "ticks_ok", "start_writes_ok",
                                    "periods_ok", "lost", "keyons", "tick_latency_ms_max", "emulator_s")
                if k in rep}
        print(f"{i:3d} {name:12s} {nch} ch: {'PASS' if ok else 'FAIL'} {keep}"
              + (f" (model: {song.problems[0][:90]})" if song.problems else ""), flush=True)
        if not ok:
            print("     " + json.dumps({k: rep[k] for k in rep if k not in keep}, default=str)[:1500])
    print(f"self test: {npass}/{len(songs)} PASS")
    return npass == len(songs)


# ---------------------------------------------------------------- openMSX
TCL = r"""
set renderer none
set throttle off
set ::work {%(work)s}
set ::f [open $::work/trace.txt w]
proc io_w {} {
    puts $::f "[machine_info time] $::wp_last_address $::wp_last_value"
}
proc finish {} {
    record stop
    foreach c {%(chans)s} { set "::%(dev)s_ch${c}_record" "" }
    puts $::f "end [machine_info time] ticks [debug read memory %(ticks)d] [debug read memory [expr {%(ticks)d + 1}]]"
    close $::f
    after time 0.1 exit
}
proc phase {} {
    set p $::wp_last_value
    puts $::f "phase $p [machine_info time] blocks [debug read memory 0xC001]"
    if {$p == 2} {
        set fb [open $::work/sram.bin wb]
        fconfigure $fb -translation binary
        puts -nonewline $fb [debug read_block {%(dev)s mem} 0x200000 %(nimg)d]
        close $fb
        debug set_watchpoint write_io {0x7E 0x7F} {} io_w
        debug set_watchpoint write_io {0xC4 0xC5} {} io_w
        record start -audioonly $::work/mix.wav
        foreach c {%(chans)s} { set "::%(dev)s_ch${c}_record" $::work/ch$c.wav }
        puts $::f "rec [machine_info time]"
    }
    if {$p == 3} { after time 0.3 finish }
    if {$p == 238} { after time 0.1 finish }
}
# the phase byte is watched from the cartridge's start on (the BIOS tests that RAM)
set ::armed 0
debug set_bp %(init)d {} {
    if {!$::armed} {
        set ::armed 1
        puts $::f "init [machine_info time]"
        debug set_watchpoint write_mem 0xC000 {} phase
    }
}
after time %(limit)f finish
"""


def run_openmsx(rom, work, song, labels):
    tcl = os.path.join(work, "run.tcl")
    chans = " ".join(str(o + 1) for o in sorted(song.used_channels()))
    open(tcl, "w").write(TCL % dict(work=work, chans=chans, dev=WAVE_DEV, ticks=labels["mp_ticks"],
                                    init=labels["init"], limit=song.seconds + 25, nimg=len(song.image)))
    return openmsx(["-machine", "C-BIOS_V9968_JP", "-ext", "moonsound_test", "-cart", rom,
                    "-romtype", "ASCII16", "-script", tcl], work, 900)


def openmsx(args, work, timeout):
    for f in ("trace.txt", "mix.wav", "sram.bin") + tuple(f"ch{o + 1}.wav" for o in range(24)):
        if os.path.exists(os.path.join(work, f)):
            os.remove(os.path.join(work, f))
    while int(subprocess.run(["pgrep", "-c", "openmsx"], capture_output=True, text=True).stdout or 0) >= 2:
        time.sleep(2)                               # never more than 2 openMSX at once (7 GB of RAM)
    env = dict(os.environ, SDL_VIDEODRIVER="dummy", SDL_AUDIODRIVER="dummy")
    env.setdefault("OPENMSX_SYSTEM_DATA", os.path.expanduser("~/openMSX/share"))
    t0 = time.time()
    with open(os.path.join(work, "openmsx.log"), "w") as log:
        subprocess.run([OPENMSX] + args, env=env, stdout=log, stderr=subprocess.STDOUT, timeout=timeout)
    return time.time() - t0


ROM_TCL = r"""
set renderer none
set throttle off
set ::work {%(work)s}
set ::f [open $::work/trace.txt w]
set ::on 0
set ::last 0
set ::gaps {}
set ::done 0
proc note {what} {
    if {!$::done} { puts $::f "$what [machine_info time]" }
}
proc io_w {} {
    if {!$::done} { puts $::f "[machine_info time] $::wp_last_address $::wp_last_value" }
}
proc poll {} {
    if {!$::on} return
    set t [machine_info time]
    if {$::last > 0} {
        set g [expr {$t - $::last}]
        if {$g > 0.0004} { lappend ::gaps "$g $t" }
    }
    set ::last $t
}
proc finish {} {
    if {$::done} return
    set ::done 1
    record stop
    foreach c {%(chans)s} { set "::%(dev)s_ch${c}_record" "" }
    foreach g $::gaps { puts $::f "gap $g" }
    puts $::f "end [machine_info time]"
    close $::f
    after time 0.1 exit
}
proc start {} {
    if {$::on} return
    set ::on 1
    set ::last 0
    set fb [open $::work/sram.bin wb]
    fconfigure $fb -translation binary
    puts -nonewline $fb [debug read_block {%(dev)s mem} 0x200000 %(nimg)d]
    close $fb
    debug set_watchpoint write_io {0x7E 0x7F} {} io_w
    debug set_watchpoint write_io {0xC4 0xC5} {} io_w
    record start -audioonly $::work/mix.wav
    foreach c {%(chans)s} { set "::%(dev)s_ch${c}_record" $::work/ch$c.wav }
    puts $::f "rec [machine_info time]"
}
set ::up0 0
debug set_bp %(us_page)d {} { if {!$::up0} { set ::up0 1; note up0 } }
debug set_bp %(us_done)d {} { note up1 }
debug set_bp %(op_menu)d {} { note menu }
debug set_bp %(demo_init)d {} { note d }
debug set_bp %(fl_flip)d {} { note f }
debug set_bp %(mod_start)d {} start
debug set_bp %(mod_poll)d {} poll
debug set_bp %(mp_end)d {} { if {$::on} { after time 0.3 finish } }
after time %(key)f { keymatrixdown 0 0x02 }
after time [expr {%(key)f + 0.2}] { keymatrixup 0 0x02 }
after time %(limit)f finish
"""


def run_openmsx_rom(rom, work, song, labels, ext, key_at):
    """The demo ROM, with the MoonSound: the crawl in English, its music
    recorded from mod_start to the MOD's stop (see ROM_TCL)."""
    tcl = os.path.join(work, "run.tcl")
    chans = " ".join(str(o + 1) for o in sorted(song.used_channels()))
    names = ("us_page", "us_done", "op_menu", "demo_init", "fl_flip", "mod_start", "mod_poll", "mp_end")
    open(tcl, "w").write(ROM_TCL % dict(work=work, chans=chans, dev=WAVE_DEV, key=key_at, nimg=len(song.image),
                                        limit=key_at + song.seconds + 30, **{k: labels[k] for k in names}))
    return openmsx(["-machine", "C-BIOS_V9968_JP"] + [x for e in ext.split() for x in ("-ext", e)]
                   + ["-cart", rom, "-romtype", "ASCII16", "-script", tcl], work, 1800)


def flip_blanks(events):
    """d/f time events -> per demo, the vertical blanks between its flips."""
    out, last = [], None
    for k, t in events:
        if k == "d":
            out.append([])
            last = None
        elif k == "f" and out:
            if last is not None:
                out[-1].append(round((t - last) * 21477270 / (1368 * 262)))
            last = t
    return out


def parse_trace(path):
    """-> dict(phase times, rec time, wave writes [(t, reg, val)], fm writes [(t, reg, val)];
    with --rom: flips and demo_inits (ev), upload and menu times, poll gaps)."""
    out = dict(phase={}, wave=[], fm=[], rec=None, end=None, ev=[], gaps=[])
    wsel = fsel = None
    for line in open(path):
        p = line.split()
        if p[0] == "init":
            out["init"] = float(p[1])
        elif p[0] == "phase":
            out["phase"][int(p[1])] = float(p[2])
            out["blocks"] = int(p[4])
        elif p[0] == "rec":
            out["rec"] = float(p[1])
        elif p[0] == "end":
            out["end"] = float(p[1])
        elif p[0] in ("d", "f"):
            out["ev"].append((p[0], float(p[1])))
        elif p[0] in ("up0", "up1", "menu"):
            out.setdefault(p[0], float(p[1]))
        elif p[0] == "gap":
            out["gaps"].append((float(p[1]), float(p[2])))
        else:
            t, port, val = float(p[0]), int(p[1]) & 0xFF, int(p[2])
            if port == 0x7E:
                wsel = val
            elif port == 0x7F:
                out["wave"].append((t, wsel, val))
            elif port == 0xC4:
                fsel = val
            elif port == 0xC5:
                out["fm"].append((t, fsel, val))
    return out


def check_trace(song, tr):
    """The writes of each tick against modplay.py; tick and key-on times."""
    fm = tr["fm"]
    start = next(t for t, r, v in fm if r == 4 and v == 0x42)     # timer 2 started: tick 0
    # the END (or mod_stop) stops the timers (60h): writes up to there
    stop = next((t for t, r, v in fm if r == 4 and v == 0x60 and t > start), float("inf"))
    clears = [t for t, r, v in fm if r == 4 and v == 0x80 and start < t < stop]
    entry = max(t for t, r, v in fm if r == 3 and t < start) - 0.05   # (mod_start's writes: the 50 ms before)
    periods = [(t, (256 - v) or 256) for t, r, v in fm if r == 3 and entry < t < stop]
    marks = [start] + clears                        # tick k's writes follow marks[k]
    got = [[] for _ in range(len(marks))]
    init = []
    k = 0
    for t, r, v in tr["wave"]:
        if t > stop:
            continue
        while k + 1 < len(marks) and t >= marks[k + 1]:
            k += 1
        (got[k] if t >= start else init).append((r, v))
    stopped = stop < float("inf")
    bad, last_ok = opl4emu.match_ticks(got, song.writes, song.heads, stopped)
    counts = [c for _, c in periods]
    ideal, real = song.times()
    # the OPL4 timer's tick starts (from the periods written) and ProTracker's
    import numpy as np
    n = min(len(clears) + 1, len(real))
    exp_timer = np.array(real[:n]) + start
    got_ticks = np.array([start] + clears[:n - 1])
    lat = got_ticks[1:] - exp_timer[1:len(got_ticks)]
    pt = np.array(ideal[:len(got_ticks)]) + start
    drift = got_ticks - pt
    # key-on times against ProTracker's time of their tick
    kon = []
    k = 0
    for t, r, v in tr["wave"]:
        if t < start:
            continue
        while k + 1 < len(marks) and t >= marks[k + 1]:
            k += 1
        if 0x68 <= r < 0x68 + 24 and v & 0x80 and k < len(ideal):
            kon.append((k, (r - 0x68) % 8, t - (start + ideal[k])))
    kerr = np.array([e for _, _, e in kon])
    first = (bad[0] if bad else len(got) - 1) if bad or not last_ok else None
    return dict(
        ticks_model=len(song.writes) - 1, ticks_seen=len(marks), ticks_ok=not bad and last_ok,
        first_mismatch=first, stopped_before_end=stopped and len(got) < len(song.writes),
        mismatch_detail=(first, got[first][:12], (song.writes[first] if first < len(song.writes) else [])[:12])
        if first is not None else None,
        start_writes=len(init), start_writes_ok=init[-len(song.writes_start):] == song.writes_start,
        periods_ok=counts[:len(song.counts)] == song.counts[:len(counts)], periods_seen=len(counts),
        timer_latency_us=dict(min=float(lat.min() * 1e6), max=float(lat.max() * 1e6), mean=float(lat.mean() * 1e6)),
        vs_protracker_ms=dict(min=float(drift.min() * 1e3), max=float(drift.max() * 1e3),
                              first_10s=float(np.abs(drift[pt < start + 10]).max() * 1e3),
                              last_10s=float(np.abs(drift[pt > pt[-1] - 10]).max() * 1e3)),
        keyon=len(kon),
        keyon_vs_protracker_ms=dict(min=float(kerr.min() * 1e3), max=float(kerr.max() * 1e3),
                                    mean=float(kerr.mean() * 1e3)),
        start=start, end=tr["end"]), kon


# ---------------------------------------------------------------- OpenMPT
def solo_mod(data, keep):
    """A copy of the MOD with the notes of every channel but `keep` removed
    (their effects stay: speed, tempo and breaks still apply)."""
    d = bytearray(data)
    nch = modplay.music.mod_channels(d)
    npat = max(d[952:1080]) + 1
    for p in range(npat):
        for r in range(64):
            for c in range(nch):
                if c == keep:
                    continue
                o = 1084 + ((p * 64 + r) * nch + c) * 4
                d[o] = 0
                d[o + 1] = 0
                d[o + 2] &= 0x0F
    return bytes(d)


def openmpt(mod_bytes, name, work, seconds, linear=True):
    """openmpt123 render. linear: the measuring reference (linear
    interpolation like the OPL4, no Amiga resampler or filter, no volume
    ramping, stereo separation 200 %: the Amiga's hard panning; OpenMPT's
    100 % puts MOD channels at 75 / 25). Else OpenMPT as a player plays it
    by default."""
    path = os.path.join(work, name + ".mod")
    open(path, "wb").write(mod_bytes)
    opts = (["--stereo", "200", "--filter", "2", "--ramping", "0", "--ctl", "render.resampler.emulate_amiga=0"]
            if linear else [])
    subprocess.run(["openmpt123", "--render", "--force", "--quiet", "--samplerate", str(RATE), "--channels", "2",
                    "--end-time", f"{seconds:.3f}", "--output-type", "wav"] + opts + [path],
                   check=True, stdout=subprocess.DEVNULL)
    os.remove(path)
    return path + ".wav"


def read_wav(path):
    """-> (rate, float array [n, channels])."""
    import numpy as np
    d = open(path, "rb").read()
    assert d[:4] == b"RIFF" and d[8:12] == b"WAVE", path
    i, fmt, data = 12, None, None
    while i + 8 <= len(d):
        tag, ln = d[i:i + 4], struct.unpack("<I", d[i + 4:i + 8])[0]
        body = d[i + 8:i + 8 + ln]
        if tag == b"fmt ":
            fmt = struct.unpack("<HHIIHH", body[:16])
            if fmt[0] == 0xFFFE:
                fmt = (struct.unpack("<H", body[24:26])[0],) + fmt[1:]
        elif tag == b"data":
            data = body
        i += 8 + ln + (ln & 1)
    tagf, nch, rate, _, _, bits = fmt
    if tagf == 3:
        a = np.frombuffer(data[:len(data) // 4 * 4], dtype="<f4").astype(np.float64)
    elif bits == 16:
        a = np.frombuffer(data[:len(data) // 2 * 2], dtype="<i2").astype(np.float64) / 32768
    else:
        raise ValueError(f"{path}: {bits}-bit format {tagf}")
    return rate, a[:len(a) // nch * nch].reshape(-1, nch)


def mono(a):
    return a.mean(axis=1) if a.ndim == 2 else a


# ------------------------------------------------------------------- audio
def openmpt_tick_times(song):
    """Where OpenMPT's ticks start in its render (whole samples per tick)."""
    out, s = [], 0
    for tk in song.ticks:
        out.append(s / RATE)
        s += int(RATE * 5 // (2 * tk["bpm"]))       # muldiv(rate, 5 * fract, tempo * 2 * fract), truncated
    return out


def notes_of(song, c):
    """(tick, start time ProTracker, next start or end, sample, byte offset, per, vol) of channel c."""
    ns = []
    for i, tk in enumerate(song.ticks):
        o = tk["ch"][c]
        if o["trig"]:
            ns.append([i, tk["t"], None, o["trig"][0], o["trig"][1], o["per"], o["vol"]])
        elif o.get("stop") and ns and ns[-1][2] is None:
            ns[-1][2] = tk["t"]
    end = song.ticks[-1]["t"] + song.ticks[-1]["dur"]
    for j, n in enumerate(ns):
        nxt = ns[j + 1][1] if j + 1 < len(ns) else end
        n[2] = min(n[2], nxt) if n[2] is not None else nxt
    return ns


def best_lag(x, y, maxlag):
    """Lag (samples) that best aligns x to y: x[i + lag] ~ y[i]."""
    import numpy as np
    n = len(y)
    best, bl = -2, 0
    for lag in range(-maxlag, maxlag + 1):
        a = x[maxlag + lag:maxlag + lag + n]
        if len(a) < n:
            continue
        c = np.dot(a, y) / (np.linalg.norm(a) * np.linalg.norm(y) + 1e-12)
        if c > best:
            best, bl = c, lag
    return bl, best


def pitch_ratio(x, y, cents=12.0, step=0.25):
    """The pitch of x against y in cents (x(t) best matches y(r t), r =
    2^(cents / 1200)), and the match (normalized correlation)."""
    import numpy as np
    n = len(y)
    t = np.arange(n, dtype=np.float64)
    grid = np.arange(-cents, cents + step / 2, step)
    cs = []
    for cc in grid:
        r = 2 ** (cc / 1200)
        yy = np.interp(t * r, t, y)                 # y played r times faster
        m = int(min(n, n / r)) - 2
        a, b = x[:m], yy[:m]
        cs.append(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-12))
    cs = np.array(cs)
    k = int(cs.argmax())
    if 0 < k < len(cs) - 1:
        den = cs[k - 1] - 2 * cs[k] + cs[k + 1]
        off = 0.5 * (cs[k - 1] - cs[k + 1]) / den if den < 0 else 0
    else:
        off = 0
    return float(grid[k] + off * step), float(cs[k])


def compare_channel(song, c, xm, ym, x_off, y_times):
    """Note by note: openMSX channel c (xm, aligned so that ProTracker time
    t is sample (t + x_off) * RATE) against OpenMPT's solo render (ym, tick
    times y_times)."""
    import numpy as np
    res = []
    for tick, t0, t1, smp, off, per, vol in notes_of(song, c):
        dur = t1 - t0
        if dur < 0.03 or vol == 0:
            continue
        xs = int(round((t0 + x_off) * RATE))
        ys = int(round(y_times[tick] * RATE))
        w = int(min(dur - 0.005, 0.25) * RATE)
        pad = int(0.004 * RATE)
        if xs - pad < 0 or xs + w + pad > len(xm) or ys + w > len(ym):
            continue
        y = ym[ys:ys + w]
        if np.sqrt(np.mean(y ** 2)) < 1e-4:
            continue
        lag, _ = best_lag(xm[xs - pad:xs + w + pad], ym[ys:ys + int(0.03 * RATE)], pad)
        x = xm[xs + lag:xs + lag + w]
        cents, match = pitch_ratio(x, y)
        r38, r20 = modplay.pitch_of(per)
        want = 1200 * math.log2(modplay.pitch_hz(r38, r20) / (modplay.PAULA * 4 / per))
        lv = 20 * math.log10((np.sqrt(np.mean(x ** 2)) + 1e-12) / (np.sqrt(np.mean(y ** 2)) + 1e-12))
        late = None
        if dur > 0.6:                               # the loop: the sound near the end of a long note
            a = int((min(dur, 2.0) - 0.15) * RATE)
            wl = int(0.1 * RATE)
            yl = ym[ys + a:ys + a + wl]
            xl0 = xs + lag + a
            if xl0 + wl + pad < len(xm) and ys + a + wl <= len(ym) and np.sqrt(np.mean(yl ** 2)) > 1e-4:
                lag2, c2 = best_lag(xm[xl0 - pad:xl0 + wl + pad], yl, pad)
                late = dict(match=c2, lag_ms=lag2 / RATE * 1e3,
                            level_db=20 * math.log10((np.sqrt(np.mean(xm[xl0 + lag2:xl0 + lag2 + wl] ** 2)) + 1e-12)
                                                     / (np.sqrt(np.mean(yl ** 2)) + 1e-12)))
        res.append(dict(ch=c, tick=tick, t=t0, smp=smp, off=off, per=per / 4, vol=vol, onset_ms=lag / RATE * 1e3,
                        cents=cents, cents_regs=want, match=match, level_db=lv, late=late))
    return res


def align(xm, ym, y_t0, x_guess, span=0.05):
    """Offset (s) of xm against ProTracker time, from a window at y_t0."""
    ys = int(y_t0 * RATE)
    y = ym[ys:ys + int(0.5 * RATE)]
    pad = int(span * RATE)
    xs = int((y_t0 + x_guess) * RATE)
    lag, c = best_lag(xm[xs - pad:xs + len(y) + pad], y, pad)
    return x_guess + lag / RATE, c


def frames_db(a, n=2205):
    import numpy as np
    m = len(a) // n
    r = np.sqrt((a[:m * n].reshape(m, n) ** 2).mean(axis=1))
    return 20 * np.log10(r + 1e-9)


def bands_db(x, y, edges=(250, 1000, 4000, 10000, 12000, 16000, 22050)):
    """Each band's share of the total energy, x against y (dB)."""
    import numpy as np
    out = {}
    fx, fy = np.abs(np.fft.rfft(x)) ** 2, np.abs(np.fft.rfft(y)) ** 2
    f = np.fft.rfftfreq(len(x), 1 / RATE)
    for lo, hi in zip(edges, edges[1:]):
        sel = (f >= lo) & (f < hi)
        out[f"{lo / 1000:g}-{hi / 1000:g} kHz"] = round(float(
            10 * np.log10((fx[sel].sum() / fx.sum() + 1e-15) / (fy[sel].sum() / fy.sum() + 1e-15))), 1)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("mod", nargs="?")
    ap.add_argument("--seconds", type=float, default=3420 / modplay.music.VBLANK_HZ)
    ap.add_argument("--fade", type=float, default=180 / modplay.music.VBLANK_HZ)
    ap.add_argument("--gap", type=int, default=0, help="busy loop between polls (rounds of 10.7 us)")
    ap.add_argument("--work", default=os.path.join(HERE, "out", "modplay_test"))
    ap.add_argument("--preview", default=None, help="copy the recordings and the reference here")
    ap.add_argument("--tag", default="", help="suffix of the preview file names")
    ap.add_argument("--no-openmsx", action="store_true", help="analyse the last run again")
    ap.add_argument("--rom", help="the demo ROM (build_rom.py --music MOD) instead of the test ROM")
    ap.add_argument("--labels", help="its labels (default: labels.txt / labels_98.txt next to it)")
    ap.add_argument("--ext", default="geo3d moonsound", help="--rom: the openMSX extensions")
    ap.add_argument("--key-at", type=float, default=8.5, help="--rom: when '1' (English) is pressed (s)")
    ap.add_argument("--flips-ref", help="--rom: d/f log of a reference run, to compare the crawl's flips")
    ap.add_argument("--z80", action="store_true", help="the test ROM in the Z80 emulator (no openMSX)")
    ap.add_argument("--kb", type=int, default=640, help="--z80: sample RAM of the emulated MoonSound")
    ap.add_argument("--selftest", action="store_true", help="--z80 on MODs made here (every effect)")
    ap.add_argument("--fuzz", type=int, default=12, help="--selftest: this many random MODs too")
    ap.add_argument("--seed", type=int, default=1985)
    a = ap.parse_args()
    work = os.path.abspath(a.work)
    os.makedirs(work, exist_ok=True)
    if a.selftest:
        sys.exit(0 if selftest(os.path.join(work, "self"), a.fuzz, a.seed) else 1)
    song = modplay.Song(a.mod, a.seconds, a.fade)
    print(song.summary())
    if a.z80:
        ok, rep = z80_test(song, work, a.kb, a.gap)
        print(json.dumps(rep, indent=1, default=str))
        print("Z80: " + ("PASS" if ok else "FAIL"))
        sys.exit(0 if ok else 1)
    import numpy as np
    if a.rom:
        rom = os.path.abspath(a.rom)
        lab = a.labels or os.path.join(os.path.dirname(rom), "labels_98.txt" if "_98" in os.path.basename(rom)
                                       else "labels.txt")
        labels = labels_of(lab)
        print(f"demo ROM {rom}, labels {lab}")
    else:
        rom, b0, labels = build(song, work, a.gap)
        print(f"test ROM {rom}: bank 0 {b0} bytes (module {labels['mp_new2'] + 20 - labels['mod_reset']} bytes)")
    if not a.no_openmsx:
        wall = (run_openmsx_rom(rom, work, song, labels, a.ext, a.key_at) if a.rom
                else run_openmsx(rom, work, song, labels))
        print(f"openMSX: {wall:.0f} s")
    tr = parse_trace(os.path.join(work, "trace.txt"))
    ph = tr["phase"]
    report = dict(mod=os.path.basename(a.mod), seconds=a.seconds, fade=a.fade, gap=a.gap,
                  summary=song.summary(), sram_blocks_found=tr.get("blocks"),
                  upload_s=(tr.get("up1", 0) - tr.get("up0", 0)) if a.rom else ph.get(2, 0) - ph.get(1, 0),
                  rom_mod_bytes=len(song.mod), sample_ram_bytes=len(song.image))
    chk, kon = check_trace(song, tr)
    report["trace"] = chk
    sram = os.path.join(work, "sram.bin")          # the sample RAM when the song starts
    report["sample_ram_ok"] = os.path.exists(sram) and open(sram, "rb").read() == song.image
    if a.rom:
        # the upload against the menu; the polls; the crawl's flips
        gaps = sorted(tr["gaps"], reverse=True)
        fl = flip_blanks(tr["ev"])
        crawl = fl[1] if len(fl) > 1 else []
        report["rom"] = dict(
            menu_s=tr.get("menu"), upload_first_unit_s=tr.get("up0"), upload_done_s=tr.get("up1"),
            upload_after_menu_s=(tr["up1"] - tr["menu"]) if "up1" in tr and "menu" in tr else None,
            mod_start_s=chk["start"], key_at_s=a.key_at,
            poll_gaps_ms=[(round(g * 1e3, 3), round(t - chk["start"], 3)) for g, t in gaps[:5]],
            poll_gaps_over_1ms=sum(1 for g, _ in gaps if g > 0.001),
            crawl_flips=len(crawl), crawl_blanks=sum(crawl))
        if a.flips_ref:
            ref = flip_blanks([(p[0], float(p[1])) for p in (l.split() for l in open(a.flips_ref))
                               if p and p[0] in ("d", "f")])
            rc = ref[1] if len(ref) > 1 else []
            m = min(len(crawl), len(rc))
            report["rom"]["crawl_flips_vs_ref"] = dict(
                compared=m, identical=crawl[:m] == rc[:m],
                diffs=[(j, crawl[j], rc[j]) for j in range(m) if crawl[j] != rc[j]][:5])
    print(json.dumps(report, indent=1, default=str)[:3000])

    # ---- audio: OpenMPT solo renders of the original MOD against openMSX's channels
    data = open(a.mod, "rb").read()
    span = a.seconds + 0.5
    yt = openmpt_tick_times(song)
    ideal, _ = song.times()
    start = chk["start"]
    x0 = start - tr["rec"]                          # ProTracker time 0 in the recordings (first guess)
    notes = []
    offs = []
    for c in range(song.nch):
        ref = openmpt(solo_mod(data, c), f"ref_ch{c + 1}", work, span)
        _, ym = read_wav(ref)
        xm = sum(read_wav(os.path.join(work, f"ch{o + 1}.wav"))[1] for o in (c, c + 8, c + 16))
        ym, xm = mono(ym), mono(xm)
        first = next((n for n in notes_of(song, c) if n[2] - n[1] > 0.3 and n[6]), None)
        off, cc = align(xm, ym, yt[first[0]], x0 + ideal[first[0]] - yt[first[0]]) if first else (x0, 0)
        off -= ideal[first[0]] - yt[first[0]] if first else 0
        offs.append((off, cc))
        notes += compare_channel(song, c, xm, ym, off, yt)
    on = np.array([n["onset_ms"] for n in notes])
    fade_at = a.seconds - a.fade
    clean = [n for n in notes if n["match"] > 0.9 and n["t"] + 0.3 < fade_at]   # the fade changes levels
    report["audio"] = dict(
        channel_offsets_ms=[round(o * 1e3, 3) for o, _ in offs],
        notes_compared=len(notes), notes_matched=int((np.array([n["match"] for n in notes]) > 0.9).sum()),
        notes_before_fade=len(clean))
    if clean:                                       # (none: the sound is not the MOD's)
        ce = np.array([n["cents"] - n["cents_regs"] for n in clean])
        cabs = np.array([n["cents"] for n in clean])
        lv = np.array([n["level_db"] for n in clean])
        med = float(np.median(lv))
        lates = [n["late"] for n in clean if n["late"] and n["t"] + 2.1 < fade_at]
        report["audio"].update(
            onset_ms=dict(min=float(on.min()), max=float(on.max()), mean=float(on.mean()),
                          abs_max_first_10s=float(np.abs([n["onset_ms"] for n in notes if n["t"] < 10]).max()),
                          abs_max_last_10s=float(np.abs([n["onset_ms"] for n in notes
                                                         if n["t"] > a.seconds - 10]).max())),
            cents_openmsx_vs_openmpt=dict(min=float(cabs.min()), max=float(cabs.max()),
                                          abs_p95=float(np.percentile(np.abs(cabs), 95))),
            cents_minus_register_prediction=dict(min=float(ce.min()), max=float(ce.max()),
                                                 abs_p95=float(np.percentile(np.abs(ce), 95))),
            level_db=dict(median=med, dev_min=float(lv.min() - med), dev_max=float(lv.max() - med),
                          abs_dev_p95=float(np.percentile(np.abs(lv - med), 95))),
            loops=dict(n=len(lates), match_min=float(min(lt["match"] for lt in lates)) if lates else None,
                       level_dev_max=float(max(abs(lt["level_db"] - med) for lt in lates)) if lates else None,
                       lag_ms_max=float(max(abs(lt["lag_ms"]) for lt in lates)) if lates else None))
    worst = sorted(notes, key=lambda n: n["match"])[:3]
    report["audio"]["worst_matches"] = [{k: (round(v, 3) if isinstance(v, float) else v) for k, v in n.items()
                                         if k != "late"} for n in worst]

    # ---- the mix: openMSX against OpenMPT (linear) and the plain OpenMPT render
    ref_mix = openmpt(data, "ref_mix_linear", work, span)
    ref_def = openmpt(data, "ref_mix_default", work, span, linear=False)
    _, ym = read_wav(ref_mix)
    _, yd = read_wav(ref_def)
    _, xm = read_wav(os.path.join(work, "mix.wav"))
    moff = float(np.median([o for o, _ in offs]))
    xs = int(round(moff * RATE))
    n = min(len(ym), len(xm) - xs, int((a.seconds - a.fade) * RATE))
    if xs >= 0 and n > 0:
        blk = []
        for side in (0, 1):
            fx, fy = frames_db(xm[xs:xs + n, side]), frames_db(ym[:n, side])
            loud = fy > fy.max() - 40
            gain = np.median(fx[loud] - fy[loud])
            dev = np.abs(fx[loud] - fy[loud] - gain)
            blk.append(dict(gain_db=float(gain), frame_dev_db_p95=float(np.percentile(dev, 95))))
        lags = []
        for s0 in np.arange(1.0, a.seconds - a.fade - 1, 2.0):
            i0 = int(s0 * RATE)
            y = ym[i0:i0 + int(0.25 * RATE)].sum(axis=1)
            if np.sqrt(np.mean(y ** 2)) < 1e-3:
                continue
            lag, cc = best_lag(xm[xs + i0 - 441:xs + i0 + len(y) + 441].sum(axis=1), y, 441)
            lags.append((float(s0), lag / RATE * 1e3, float(cc)))
        lg = np.array([lag for _, lag, _ in lags])
        report["mix"] = dict(sides=blk, lag_ms_every_2s=dict(n=len(lg), min=float(lg.min()), max=float(lg.max()),
                                                             first=float(lg[0]), last=float(lg[-1])))
        report["mix_lags"] = [(s, round(lag, 3), round(cc, 3)) for s, lag, cc in lags]
        tail = xm[xs + int(a.seconds * RATE) + int(0.05 * RATE):]
        report["mix"]["after_end_peak"] = float(np.abs(tail).max()) if len(tail) else None
        fade = xm[xs + int((a.seconds - a.fade) * RATE):xs + int(a.seconds * RATE)]
        report["mix"]["fade_db_per_s"] = [round(float(v), 1) for v in frames_db(fade.mean(axis=1), RATE // 2)]
        m2 = min(n, len(yd))
        x_, l_, d_ = xm[xs:xs + m2].mean(axis=1), ym[:m2].mean(axis=1), yd[:m2].mean(axis=1)
        report["spectrum"] = dict(vs_openmpt_linear=bands_db(x_, l_), vs_openmpt_default=bands_db(x_, d_),
                                  openmpt_linear_vs_default=bands_db(l_, d_))
    json.dump(dict(report, notes=notes), open(os.path.join(work, "report.json"), "w"), indent=1, default=str)
    print(json.dumps({k: report[k] for k in ("audio", "mix", "spectrum") if k in report}, indent=1, default=str))
    if a.preview:
        os.makedirs(a.preview, exist_ok=True)
        sfx = a.tag
        shutil.copy(os.path.join(work, "mix.wav"),
                    os.path.join(a.preview, f"crawl_music_MOD_MoonSound-wave{sfx}.wav" if a.rom
                                 else f"modplay_openmsx_moonsound_wave_first57s{sfx}.wav"))
        shutil.copy(ref_mix, os.path.join(a.preview, "modplay_openmpt_reference_amiga-pan_linear_first57s.wav"))
        shutil.copy(ref_def, os.path.join(a.preview, "modplay_openmpt_reference_default_first57s.wav"))
        print("preview:", a.preview)


if __name__ == "__main__":
    main()
